# Generated by Django 3.0.3 on 2020-03-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200301_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователей'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='usersAva/%Y/', verbose_name='Фото'),
        ),
    ]
