# Generated by Django 3.0.3 on 2020-03-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200305_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_image',
        ),
    ]
